
package View;

import Controller.ControllerTelaRealizaTransfusao;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Tela do sistema para registrar transfusões de sangue.
 * 
 * @author - Ruan Pereira
 * @since  - 18/12/2023
 */
public class TelaRealizaTransfusao extends javax.swing.JFrame {

    private final ControllerTelaRealizaTransfusao controller;
    private final TelaBancoSangue telaBancoSangue;
    
    /**
     * Creates new form TelaRealizaTransfusao
     * @param telaBancoSangue
     */
    public TelaRealizaTransfusao(TelaBancoSangue telaBancoSangue) {
        initComponents();
        this.controller = new ControllerTelaRealizaTransfusao(this);
        this.telaBancoSangue = telaBancoSangue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVoltar3 = new javax.swing.JButton();
        panelInfoPaciente = new javax.swing.JPanel();
        checkBoxIsPaciente = new javax.swing.JCheckBox();
        labelCpfDoador = new javax.swing.JLabel();
        inputCpfPaciente = new javax.swing.JTextField();
        labelNomeDoador = new javax.swing.JLabel();
        inputNomePaciente = new javax.swing.JTextField();
        labelNascimento = new javax.swing.JLabel();
        inputNascimento = new javax.swing.JTextField();
        inputTelefone = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        inputEndereco = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        panelInfoSangue153 = new javax.swing.JPanel();
        labelTipoSangue153 = new javax.swing.JLabel();
        labelQuantidade153 = new javax.swing.JLabel();
        inputQuantidade = new javax.swing.JTextField();
        buttonDoar = new javax.swing.JButton();
        comboBoxTipoSangue = new javax.swing.JComboBox<>();
        labelRealizarDoacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonVoltar3.setBackground(new java.awt.Color(204, 204, 204));
        buttonVoltar3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        buttonVoltar3.setForeground(new java.awt.Color(0, 0, 0));
        buttonVoltar3.setText("↩");
        buttonVoltar3.setBorder(null);
        buttonVoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltar3ActionPerformed(evt);
            }
        });

        panelInfoPaciente.setBackground(new java.awt.Color(204, 0, 0));
        panelInfoPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        panelInfoPaciente.setForeground(new java.awt.Color(51, 51, 51));

        checkBoxIsPaciente.setBackground(new java.awt.Color(204, 0, 0));
        checkBoxIsPaciente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkBoxIsPaciente.setForeground(new java.awt.Color(0, 0, 0));
        checkBoxIsPaciente.setText("Já é Paciente?");
        checkBoxIsPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxIsPacienteActionPerformed(evt);
            }
        });

        labelCpfDoador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelCpfDoador.setForeground(new java.awt.Color(0, 0, 0));
        labelCpfDoador.setText("CPF do(a) Paciente:");

        inputCpfPaciente.setBackground(new java.awt.Color(255, 255, 255));
        inputCpfPaciente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputCpfPaciente.setForeground(new java.awt.Color(51, 51, 51));
        inputCpfPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCpfPacienteActionPerformed(evt);
            }
        });

        labelNomeDoador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNomeDoador.setForeground(new java.awt.Color(0, 0, 0));
        labelNomeDoador.setText("Nome do(a) Paciente:");

        inputNomePaciente.setBackground(new java.awt.Color(255, 255, 255));
        inputNomePaciente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputNomePaciente.setForeground(new java.awt.Color(51, 51, 51));
        inputNomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomePacienteActionPerformed(evt);
            }
        });

        labelNascimento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNascimento.setForeground(new java.awt.Color(0, 0, 0));
        labelNascimento.setText("Data de Nascimento:");

        inputNascimento.setBackground(new java.awt.Color(255, 255, 255));
        inputNascimento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputNascimento.setForeground(new java.awt.Color(51, 51, 51));
        inputNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNascimentoActionPerformed(evt);
            }
        });

        inputTelefone.setBackground(new java.awt.Color(255, 255, 255));
        inputTelefone.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputTelefone.setForeground(new java.awt.Color(51, 51, 51));
        inputTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelefoneActionPerformed(evt);
            }
        });

        labelTelefone.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTelefone.setForeground(new java.awt.Color(0, 0, 0));
        labelTelefone.setText("Telefone:");

        labelEmail.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(0, 0, 0));
        labelEmail.setText("Email:");

        inputEmail.setBackground(new java.awt.Color(255, 255, 255));
        inputEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputEmail.setForeground(new java.awt.Color(51, 51, 51));
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });

        inputEndereco.setBackground(new java.awt.Color(255, 255, 255));
        inputEndereco.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputEndereco.setForeground(new java.awt.Color(51, 51, 51));
        inputEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEnderecoActionPerformed(evt);
            }
        });

        labelEndereco.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelEndereco.setForeground(new java.awt.Color(0, 0, 0));
        labelEndereco.setText("Endereço:");

        javax.swing.GroupLayout panelInfoPacienteLayout = new javax.swing.GroupLayout(panelInfoPaciente);
        panelInfoPaciente.setLayout(panelInfoPacienteLayout);
        panelInfoPacienteLayout.setHorizontalGroup(
            panelInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoPacienteLayout.createSequentialGroup()
                        .addGroup(panelInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNomeDoador)
                            .addComponent(labelNascimento))
                        .addGap(12, 12, 12)
                        .addGroup(panelInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(inputNomePaciente)))
                    .addGroup(panelInfoPacienteLayout.createSequentialGroup()
                        .addComponent(labelTelefone)
                        .addGap(117, 117, 117)
                        .addComponent(inputTelefone))
                    .addGroup(panelInfoPacienteLayout.createSequentialGroup()
                        .addComponent(labelEmail)
                        .addGap(145, 145, 145)
                        .addComponent(inputEmail))
                    .addGroup(panelInfoPacienteLayout.createSequentialGroup()
                        .addComponent(labelEndereco)
                        .addGap(110, 110, 110)
                        .addComponent(inputEndereco))
                    .addGroup(panelInfoPacienteLayout.createSequentialGroup()
                        .addComponent(checkBoxIsPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelInfoPacienteLayout.createSequentialGroup()
                        .addComponent(labelCpfDoador)
                        .addGap(28, 28, 28)
                        .addComponent(inputCpfPaciente)))
                .addContainerGap())
        );
        panelInfoPacienteLayout.setVerticalGroup(
            panelInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxIsPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNomeDoador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpfDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelInfoSangue153.setBackground(new java.awt.Color(204, 0, 0));
        panelInfoSangue153.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Sangue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        labelTipoSangue153.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTipoSangue153.setForeground(new java.awt.Color(0, 0, 0));
        labelTipoSangue153.setText("Tipo Sanguineo:");

        labelQuantidade153.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelQuantidade153.setForeground(new java.awt.Color(0, 0, 0));
        labelQuantidade153.setText("Quantidade:");

        inputQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        inputQuantidade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputQuantidade.setForeground(new java.awt.Color(51, 51, 51));
        inputQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputQuantidadeActionPerformed(evt);
            }
        });

        buttonDoar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonDoar.setForeground(new java.awt.Color(0, 0, 0));
        buttonDoar.setText("Doar");
        buttonDoar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDoarActionPerformed(evt);
            }
        });

        comboBoxTipoSangue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        comboBoxTipoSangue.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxTipoSangue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O Positivo", "O Negativo", "A Positivo", "A Negativo", "B Positivo", "B negativo", "AB Positivo", "AB Negativo" }));

        javax.swing.GroupLayout panelInfoSangue153Layout = new javax.swing.GroupLayout(panelInfoSangue153);
        panelInfoSangue153.setLayout(panelInfoSangue153Layout);
        panelInfoSangue153Layout.setHorizontalGroup(
            panelInfoSangue153Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoSangue153Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoSangue153Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoSangue153Layout.createSequentialGroup()
                        .addComponent(labelTipoSangue153)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxTipoSangue, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoSangue153Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonDoar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoSangue153Layout.createSequentialGroup()
                        .addComponent(labelQuantidade153)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelInfoSangue153Layout.setVerticalGroup(
            panelInfoSangue153Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoSangue153Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelInfoSangue153Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoSangue153, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTipoSangue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoSangue153Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQuantidade153, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(buttonDoar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelRealizarDoacao.setBackground(new java.awt.Color(255, 255, 255));
        labelRealizarDoacao.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelRealizarDoacao.setForeground(new java.awt.Color(0, 0, 0));
        labelRealizarDoacao.setText("Doar para Paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInfoPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRealizarDoacao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelInfoSangue153, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRealizarDoacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInfoSangue153, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltar3ActionPerformed
        dispose();
    }//GEN-LAST:event_buttonVoltar3ActionPerformed

    private void checkBoxIsPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxIsPacienteActionPerformed
        this.getInputNomePaciente().setVisible(!this.getCheckBoxIsPaciente().isSelected());
        this.getInputNascimento().setVisible(!this.getCheckBoxIsPaciente().isSelected());
        this.getInputTelefone().setVisible(!this.getCheckBoxIsPaciente().isSelected());
        this.getInputEmail().setVisible(!this.getCheckBoxIsPaciente().isSelected());
        this.getInputEndereco().setVisible(!this.getCheckBoxIsPaciente().isSelected());
        
        this.getLabelNomeDoador().setVisible(!this.getCheckBoxIsPaciente().isSelected());
        this.getLabelNascimento().setVisible(!this.getCheckBoxIsPaciente().isSelected());
        this.getLabelTelefone().setVisible(!this.getCheckBoxIsPaciente().isSelected());
        this.getLabelEmail().setVisible(!this.getCheckBoxIsPaciente().isSelected());
        this.getLabelEndereco().setVisible(!this.getCheckBoxIsPaciente().isSelected());
    }//GEN-LAST:event_checkBoxIsPacienteActionPerformed

    private void inputCpfPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCpfPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCpfPacienteActionPerformed

    private void inputNomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomePacienteActionPerformed

    private void inputNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNascimentoActionPerformed

    private void inputTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefoneActionPerformed

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void inputEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEnderecoActionPerformed

    private void inputQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputQuantidadeActionPerformed

    private void buttonDoarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDoarActionPerformed
        if (this.getController().validaCampos()) {
            if (this.getController().cadastrar()) {
                JOptionPane.showMessageDialog(null, "Doação realizada com sucesso!");
                this.telaBancoSangue.getController().atualizarTabela();
                this.limpaCampos();
            }
        }
    }//GEN-LAST:event_buttonDoarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRealizaTransfusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRealizaTransfusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRealizaTransfusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRealizaTransfusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDoar;
    private javax.swing.JButton buttonVoltar3;
    private javax.swing.JCheckBox checkBoxIsPaciente;
    private javax.swing.JComboBox<String> comboBoxTipoSangue;
    private javax.swing.JTextField inputCpfPaciente;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputEndereco;
    private javax.swing.JTextField inputNascimento;
    private javax.swing.JTextField inputNomePaciente;
    private javax.swing.JTextField inputQuantidade;
    private javax.swing.JTextField inputTelefone;
    private javax.swing.JLabel labelCpfDoador;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelNascimento;
    private javax.swing.JLabel labelNomeDoador;
    private javax.swing.JLabel labelQuantidade153;
    private javax.swing.JLabel labelRealizarDoacao;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTipoSangue153;
    private javax.swing.JPanel panelInfoPaciente;
    private javax.swing.JPanel panelInfoSangue153;
    // End of variables declaration//GEN-END:variables

    /**
     * Limpas todos os campos da tela
     * @return void
     */
    private void limpaCampos() {
        this.getInputNomePaciente().setText("");
        this.getInputCpfPaciente().setText("");
        this.getInputNascimento().setText("");
        this.getInputTelefone().setText("");
        this.getInputEmail().setText("");
        this.getInputEndereco().setText("");
        this.getInputQuantidade().setText("");
    }
    
    public ControllerTelaRealizaTransfusao getController() {
        return controller;
    }

    public JButton getButtonDoar() {
        return buttonDoar;
    }

    public void setButtonDoar(JButton buttonDoar) {
        this.buttonDoar = buttonDoar;
    }

    public JButton getButtonVoltar3() {
        return buttonVoltar3;
    }

    public void setButtonVoltar3(JButton buttonVoltar3) {
        this.buttonVoltar3 = buttonVoltar3;
    }

    public JCheckBox getCheckBoxIsPaciente() {
        return checkBoxIsPaciente;
    }

    public void setCheckBoxIsPaciente(JCheckBox checkBoxIsPaciente) {
        this.checkBoxIsPaciente = checkBoxIsPaciente;
    }

    public JComboBox<String> getComboBoxTipoSangue() {
        return comboBoxTipoSangue;
    }

    public void setComboBoxTipoSangue(JComboBox<String> comboBoxTipoSangue) {
        this.comboBoxTipoSangue = comboBoxTipoSangue;
    }

    public JTextField getInputCpfPaciente() {
        return inputCpfPaciente;
    }

    public void setInputCpfPaciente(JTextField inputCpfPaciente) {
        this.inputCpfPaciente = inputCpfPaciente;
    }

    public JTextField getInputEmail() {
        return inputEmail;
    }

    public void setInputEmail(JTextField inputEmail) {
        this.inputEmail = inputEmail;
    }

    public JTextField getInputEndereco() {
        return inputEndereco;
    }

    public void setInputEndereco(JTextField inputEndereco) {
        this.inputEndereco = inputEndereco;
    }

    public JTextField getInputNascimento() {
        return inputNascimento;
    }

    public void setInputNascimento(JTextField inputNascimento) {
        this.inputNascimento = inputNascimento;
    }

    public JTextField getInputNomePaciente() {
        return inputNomePaciente;
    }

    public void setInputNomePaciente(JTextField inputNomePaciente) {
        this.inputNomePaciente = inputNomePaciente;
    }

    public JTextField getInputQuantidade() {
        return inputQuantidade;
    }

    public void setInputQuantidade(JTextField inputQuantidade) {
        this.inputQuantidade = inputQuantidade;
    }

    public JTextField getInputTelefone() {
        return inputTelefone;
    }

    public void setInputTelefone(JTextField inputTelefone) {
        this.inputTelefone = inputTelefone;
    }

    public JLabel getLabelCpfDoador() {
        return labelCpfDoador;
    }

    public void setLabelCpfDoador(JLabel labelCpfDoador) {
        this.labelCpfDoador = labelCpfDoador;
    }

    public JLabel getLabelEmail() {
        return labelEmail;
    }

    public void setLabelEmail(JLabel labelEmail) {
        this.labelEmail = labelEmail;
    }

    public JLabel getLabelEndereco() {
        return labelEndereco;
    }

    public void setLabelEndereco(JLabel labelEndereco) {
        this.labelEndereco = labelEndereco;
    }

    public JLabel getLabelNascimento() {
        return labelNascimento;
    }

    public void setLabelNascimento(JLabel labelNascimento) {
        this.labelNascimento = labelNascimento;
    }

    public JLabel getLabelNomeDoador() {
        return labelNomeDoador;
    }

    public void setLabelNomeDoador(JLabel labelNomeDoador) {
        this.labelNomeDoador = labelNomeDoador;
    }

    public JLabel getLabelQuantidade153() {
        return labelQuantidade153;
    }

    public void setLabelQuantidade153(JLabel labelQuantidade153) {
        this.labelQuantidade153 = labelQuantidade153;
    }

    public JLabel getLabelRealizarDoacao() {
        return labelRealizarDoacao;
    }

    public void setLabelRealizarDoacao(JLabel labelRealizarDoacao) {
        this.labelRealizarDoacao = labelRealizarDoacao;
    }

    public JLabel getLabelTelefone() {
        return labelTelefone;
    }

    public void setLabelTelefone(JLabel labelTelefone) {
        this.labelTelefone = labelTelefone;
    }

    public JLabel getLabelTipoSangue153() {
        return labelTipoSangue153;
    }

    public void setLabelTipoSangue153(JLabel labelTipoSangue153) {
        this.labelTipoSangue153 = labelTipoSangue153;
    }

    public JPanel getPanelInfoPaciente() {
        return panelInfoPaciente;
    }

    public void setPanelInfoPaciente(JPanel panelInfoPaciente) {
        this.panelInfoPaciente = panelInfoPaciente;
    }

    public JPanel getPanelInfoSangue153() {
        return panelInfoSangue153;
    }

    public void setPanelInfoSangue153(JPanel panelInfoSangue153) {
        this.panelInfoSangue153 = panelInfoSangue153;
    }

    
}
