
package View;

import Controller.ControllerTelaBancoSangue;
import Model.ModelFuncionarioPermissao;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 * Tela do sistema que apresenta a tabela do banco de sangues coletados
 * 
 * @author - Ruan Pereira
 * @since  - 18/12/2023
 */
public class TelaBancoSangue extends javax.swing.JFrame {

    private final ControllerTelaBancoSangue controller;
    
    /**
     * Creates new form TabelaBancoSangue
     * @param funcionarioPermissao
     */
    public TelaBancoSangue(ModelFuncionarioPermissao funcionarioPermissao) {
        initComponents();
        this.controller = new ControllerTelaBancoSangue(this, funcionarioPermissao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBancoSangue = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBancoSangue = new javax.swing.JTable();
        buttonRealizarDoacao = new javax.swing.JButton();
        buttonCadastrarDoacao = new javax.swing.JButton();
        buttonVoltar7 = new javax.swing.JButton();
        labelBancoSangue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBancoSangue.setBackground(new java.awt.Color(153, 204, 255));

        tableBancoSangue.setBackground(new java.awt.Color(255, 255, 255));
        tableBancoSangue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tableBancoSangue.setForeground(new java.awt.Color(51, 51, 51));
        tableBancoSangue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBancoSangue.setAutoscrolls(false);
        tableBancoSangue.setShowGrid(true);
        jScrollPane1.setViewportView(tableBancoSangue);

        buttonRealizarDoacao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonRealizarDoacao.setForeground(new java.awt.Color(0, 0, 0));
        buttonRealizarDoacao.setText("Doar Para Paciente");
        buttonRealizarDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRealizarDoacaoActionPerformed(evt);
            }
        });

        buttonCadastrarDoacao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonCadastrarDoacao.setForeground(new java.awt.Color(0, 0, 0));
        buttonCadastrarDoacao.setText("Cadastrar Doação");
        buttonCadastrarDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarDoacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBancoSangueLayout = new javax.swing.GroupLayout(panelBancoSangue);
        panelBancoSangue.setLayout(panelBancoSangueLayout);
        panelBancoSangueLayout.setHorizontalGroup(
            panelBancoSangueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBancoSangueLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(buttonCadastrarDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(buttonRealizarDoacao)
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBancoSangueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelBancoSangueLayout.setVerticalGroup(
            panelBancoSangueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBancoSangueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(panelBancoSangueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRealizarDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCadastrarDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        buttonVoltar7.setBackground(new java.awt.Color(204, 204, 204));
        buttonVoltar7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        buttonVoltar7.setForeground(new java.awt.Color(0, 0, 0));
        buttonVoltar7.setText("↩");
        buttonVoltar7.setBorder(null);
        buttonVoltar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltar7ActionPerformed(evt);
            }
        });

        labelBancoSangue.setBackground(new java.awt.Color(255, 255, 255));
        labelBancoSangue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelBancoSangue.setForeground(new java.awt.Color(0, 0, 0));
        labelBancoSangue.setText("Banco de Sangue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonVoltar7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBancoSangue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelBancoSangue)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonVoltar7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBancoSangue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBancoSangue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRealizarDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRealizarDoacaoActionPerformed
        TelaRealizaTransfusao telaRealizaTransfusao = new TelaRealizaTransfusao(this);
        telaRealizaTransfusao.setVisible(true);
    }//GEN-LAST:event_buttonRealizarDoacaoActionPerformed

    private void buttonCadastrarDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarDoacaoActionPerformed
        TelaCadastroDoacao telaCadastroDoacao = new TelaCadastroDoacao(this);
        telaCadastroDoacao.setVisible(true);
    }//GEN-LAST:event_buttonCadastrarDoacaoActionPerformed

    private void buttonVoltar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltar7ActionPerformed
        dispose();
    }//GEN-LAST:event_buttonVoltar7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBancoSangue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBancoSangue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBancoSangue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBancoSangue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarDoacao;
    private javax.swing.JButton buttonRealizarDoacao;
    private javax.swing.JButton buttonVoltar7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBancoSangue;
    private javax.swing.JPanel panelBancoSangue;
    private javax.swing.JTable tableBancoSangue;
    // End of variables declaration//GEN-END:variables

    public ControllerTelaBancoSangue getController() {
        return controller;
    }

    public JButton getButtonCadastrarDoacao() {
        return buttonCadastrarDoacao;
    }

    public JButton getButtonRealizarDoacao() {
        return buttonRealizarDoacao;
    }

    public JButton getButtonVoltar7() {
        return buttonVoltar7;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLabelBancoSangue() {
        return labelBancoSangue;
    }

    public JPanel getPanelBancoSangue() {
        return panelBancoSangue;
    }

    public JTable getTableBancoSangue() {
        return tableBancoSangue;
    }
    
}
