
package View;

import Controller.ControllerTelaLogin;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Classe responsável pela tela de login do sistema
 * 
 * @author - Ruan Pereira
 * @since  - 18/12/2023
 */
public class TelaLogin extends javax.swing.JFrame {

    private ControllerTelaLogin controller;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        this.controller = new ControllerTelaLogin(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTelaLogin = new javax.swing.JPanel();
        labelNomeFuncionario = new javax.swing.JLabel();
        inputNomeFuncionario = new javax.swing.JTextField();
        labelCpfFuncionario = new javax.swing.JLabel();
        inputCpfFuncionario = new javax.swing.JTextField();
        buttonAcessar = new javax.swing.JButton();
        labelTelaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");
        setBackground(new java.awt.Color(255, 255, 255));

        panelTelaLogin.setBackground(new java.awt.Color(153, 204, 255));

        labelNomeFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        labelNomeFuncionario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelNomeFuncionario.setForeground(new java.awt.Color(51, 51, 51));
        labelNomeFuncionario.setText("Nome do Funcionário:");

        inputNomeFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        inputNomeFuncionario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inputNomeFuncionario.setForeground(new java.awt.Color(51, 51, 51));
        inputNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeFuncionarioActionPerformed(evt);
            }
        });

        labelCpfFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        labelCpfFuncionario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelCpfFuncionario.setForeground(new java.awt.Color(51, 51, 51));
        labelCpfFuncionario.setText("CPF do Funcionário:");

        inputCpfFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        inputCpfFuncionario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inputCpfFuncionario.setForeground(new java.awt.Color(51, 51, 51));
        inputCpfFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCpfFuncionarioActionPerformed(evt);
            }
        });

        buttonAcessar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonAcessar.setText("Acessar");
        buttonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcessarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTelaLoginLayout = new javax.swing.GroupLayout(panelTelaLogin);
        panelTelaLogin.setLayout(panelTelaLoginLayout);
        panelTelaLoginLayout.setHorizontalGroup(
            panelTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaLoginLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(panelTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNomeFuncionario)
                    .addComponent(labelCpfFuncionario))
                .addGap(27, 27, 27)
                .addGroup(panelTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTelaLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        panelTelaLoginLayout.setVerticalGroup(
            panelTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaLoginLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(panelTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomeFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpfFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addComponent(buttonAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        labelTelaLogin.setBackground(new java.awt.Color(255, 255, 255));
        labelTelaLogin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelTelaLogin.setForeground(new java.awt.Color(0, 0, 0));
        labelTelaLogin.setText("Acessar o Banco de Sangue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTelaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTelaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeFuncionarioActionPerformed

    private void inputCpfFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCpfFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCpfFuncionarioActionPerformed

    private void buttonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcessarActionPerformed
        if (this.getController().validaLogin()) {
            TelaMenuPrincipal telaMenuPrincipal = new TelaMenuPrincipal(this.getController().getModelFuncionario());
            telaMenuPrincipal.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_buttonAcessarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAcessar;
    private javax.swing.JTextField inputCpfFuncionario;
    private javax.swing.JTextField inputNomeFuncionario;
    private javax.swing.JLabel labelCpfFuncionario;
    private javax.swing.JLabel labelNomeFuncionario;
    private javax.swing.JLabel labelTelaLogin;
    private javax.swing.JPanel panelTelaLogin;
    // End of variables declaration//GEN-END:variables
    
    public ControllerTelaLogin getController() {
        return this.controller;
    }

    public void setController(ControllerTelaLogin controller) {
        this.controller = controller;
    }

    public JButton getButtonAcessar() {
        return buttonAcessar;
    }

    public void setButtonAcessar(JButton buttonAcessar) {
        this.buttonAcessar = buttonAcessar;
    }

    public JTextField getInputCpfFuncionario() {
        return inputCpfFuncionario;
    }

    public void setInputCpfFuncionario(JTextField inputCpfFuncionario) {
        this.inputCpfFuncionario = inputCpfFuncionario;
    }

    public JTextField getInputNomeFuncionario() {
        return inputNomeFuncionario;
    }

    public void setInputNomeFuncionario(JTextField inputNomeFuncionario) {
        this.inputNomeFuncionario = inputNomeFuncionario;
    }

    public JLabel getLabelCpfFuncionario() {
        return labelCpfFuncionario;
    }

    public void setLabelCpfFuncionario(JLabel labelCpfFuncionario) {
        this.labelCpfFuncionario = labelCpfFuncionario;
    }

    public JLabel getLabelNomeFuncionario() {
        return labelNomeFuncionario;
    }

    public void setLabelNomeFuncionario(JLabel labelNomeFuncionario) {
        this.labelNomeFuncionario = labelNomeFuncionario;
    }

    public JLabel getLabelTelaLogin() {
        return labelTelaLogin;
    }

    public void setLabelTelaLogin(JLabel labelTelaLogin) {
        this.labelTelaLogin = labelTelaLogin;
    }

    public JPanel getPanelTelaLogin() {
        return panelTelaLogin;
    }

    public void setPanelTelaLogin(JPanel panelTelaLogin) {
        this.panelTelaLogin = panelTelaLogin;
    }
    
    
}
