
package View;

import Controller.ControllerTelaPermissoes;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 * Tela do sistema que apresenta a tabela dos funcionários com acesso ao sistema
 * 
 * @author - Ruan Pereira
 * @since  - 31/12/2023
 */
public class TelaPermissoes extends javax.swing.JFrame {
    
    private final ControllerTelaPermissoes controller;

    /**
     * Creates new form TelaPermissoes
     */
    public TelaPermissoes() {
        initComponents();
        this.controller = new ControllerTelaPermissoes(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFuncionarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFuncionarios = new javax.swing.JTable();
        buttonAlterarFuncionario = new javax.swing.JButton();
        buttonExcluirFuncionario = new javax.swing.JButton();
        buttonNovoFuncionario = new javax.swing.JButton();
        labelFuncionarios = new javax.swing.JLabel();
        buttonVoltar7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelFuncionarios.setBackground(new java.awt.Color(153, 204, 255));

        tableFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        tableFuncionarios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tableFuncionarios.setForeground(new java.awt.Color(51, 51, 51));
        tableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Permissão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFuncionarios.setShowGrid(true);
        jScrollPane1.setViewportView(tableFuncionarios);

        buttonAlterarFuncionario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonAlterarFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        buttonAlterarFuncionario.setText("Alterar Funcionário");
        buttonAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarFuncionarioActionPerformed(evt);
            }
        });

        buttonExcluirFuncionario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonExcluirFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        buttonExcluirFuncionario.setText("Excluir Funcionário");
        buttonExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirFuncionarioActionPerformed(evt);
            }
        });

        buttonNovoFuncionario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonNovoFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        buttonNovoFuncionario.setText("Novo Funcionário");
        buttonNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFuncionariosLayout = new javax.swing.GroupLayout(panelFuncionarios);
        panelFuncionarios.setLayout(panelFuncionariosLayout);
        panelFuncionariosLayout.setHorizontalGroup(
            panelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncionariosLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(buttonNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonExcluirFuncionario)
                .addGap(18, 18, 18)
                .addComponent(buttonAlterarFuncionario)
                .addGap(171, 171, 171))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelFuncionariosLayout.setVerticalGroup(
            panelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncionariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(panelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExcluirFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAlterarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        labelFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        labelFuncionarios.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelFuncionarios.setForeground(new java.awt.Color(0, 0, 0));
        labelFuncionarios.setText("Funcionários");

        buttonVoltar7.setBackground(new java.awt.Color(204, 204, 204));
        buttonVoltar7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        buttonVoltar7.setForeground(new java.awt.Color(0, 0, 0));
        buttonVoltar7.setText("↩");
        buttonVoltar7.setBorder(null);
        buttonVoltar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltar7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonVoltar7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFuncionarios)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonVoltar7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarFuncionarioActionPerformed
        if (this.getTableFuncionarios().getSelectedRow() != -1) {
            this.abreTelaAlterarFuncionario();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um registro para atualização.");
        }
    }//GEN-LAST:event_buttonAlterarFuncionarioActionPerformed

    private void buttonVoltar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltar7ActionPerformed
        dispose();
    }//GEN-LAST:event_buttonVoltar7ActionPerformed

    private void buttonExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirFuncionarioActionPerformed
        this.getController().excluirRegistro();
    }//GEN-LAST:event_buttonExcluirFuncionarioActionPerformed

    private void buttonNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoFuncionarioActionPerformed
        TelaCadastrarFuncionario telaCadastrarFuncionario = new TelaCadastrarFuncionario(this, false);
        telaCadastrarFuncionario.setVisible(true);
    }//GEN-LAST:event_buttonNovoFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPermissoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterarFuncionario;
    private javax.swing.JButton buttonExcluirFuncionario;
    private javax.swing.JButton buttonNovoFuncionario;
    private javax.swing.JButton buttonVoltar7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFuncionarios;
    private javax.swing.JPanel panelFuncionarios;
    private javax.swing.JTable tableFuncionarios;
    // End of variables declaration//GEN-END:variables

    /**
     * Abre a tela de Alteração com os campos preenchidos com os dados do funcionário selecionado
     */
    private void abreTelaAlterarFuncionario() {
        TelaCadastrarFuncionario telaCadastrarFuncionario = new TelaCadastrarFuncionario(this, true);
        telaCadastrarFuncionario.getLabelCadastrarFuncionario().setText("Alterar Funcionário");
        telaCadastrarFuncionario.setVisible(true);
        telaCadastrarFuncionario.getInputCpfFuncionario().setEnabled(false);
    }
    
    public ControllerTelaPermissoes getController() {
        return controller;
    }

    public JButton getButtonAlterarFuncionario() {
        return buttonAlterarFuncionario;
    }

    public void setButtonAlterarFuncionario(JButton buttonAlterarFuncionario) {
        this.buttonAlterarFuncionario = buttonAlterarFuncionario;
    }

    public JButton getButtonExcluirFuncionario() {
        return buttonExcluirFuncionario;
    }

    public void setButtonExcluirFuncionario(JButton buttonExcluirFuncionario) {
        this.buttonExcluirFuncionario = buttonExcluirFuncionario;
    }

    public JButton getButtonNovoFuncionario() {
        return buttonNovoFuncionario;
    }

    public void setButtonNovoFuncionario(JButton buttonNovoFuncionario) {
        this.buttonNovoFuncionario = buttonNovoFuncionario;
    }

    public JButton getButtonVoltar7() {
        return buttonVoltar7;
    }

    public void setButtonVoltar7(JButton buttonVoltar7) {
        this.buttonVoltar7 = buttonVoltar7;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLabelFuncionarios() {
        return labelFuncionarios;
    }

    public void setLabelFuncionarios(JLabel labelFuncionarios) {
        this.labelFuncionarios = labelFuncionarios;
    }

    public JPanel getPanelFuncionarios() {
        return panelFuncionarios;
    }

    public void setPanelFuncionarios(JPanel panelFuncionarios) {
        this.panelFuncionarios = panelFuncionarios;
    }

    public JTable getTableFuncionarios() {
        return tableFuncionarios;
    }

    public void setTableFuncionarios(JTable tableFuncionarios) {
        this.tableFuncionarios = tableFuncionarios;
    }
    
}
