
package View;

import Controller.ControllerTelaCadastroFuncionario;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Tela para cadastro de novos usuários do sistema
 * 
 * @author - Ruan Pereira
 * @since  - 31/12/2023
 */
public class TelaCadastrarFuncionario extends javax.swing.JFrame {

    private final ControllerTelaCadastroFuncionario controller;
    private final TelaPermissoes telaPermissoes;
    public final boolean isUpdate;
    
    /**
     * Creates new form TelaCadastrarFuncionario
     * @param telaPermissoes
     * @param isUpdate Indica se a tela será aberta para atualização de registro ou cadastro
     */
    public TelaCadastrarFuncionario(TelaPermissoes telaPermissoes, boolean isUpdate) {
        initComponents();
        this.telaPermissoes = telaPermissoes;
        this.isUpdate = isUpdate;
        this.controller = new ControllerTelaCadastroFuncionario(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVoltar3 = new javax.swing.JButton();
        labelCadastrarFuncionario = new javax.swing.JLabel();
        panelCadastrarFuncionario = new javax.swing.JPanel();
        labelNomeFuncionario = new javax.swing.JLabel();
        labelCpfFuncionario = new javax.swing.JLabel();
        inputCpfFuncionario = new javax.swing.JTextField();
        buttonCadastrar = new javax.swing.JButton();
        labelPermissaoFuncionario = new javax.swing.JLabel();
        comboBoxPermissaoFuncionario = new javax.swing.JComboBox<>();
        inputNomeFuncionario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonVoltar3.setBackground(new java.awt.Color(204, 204, 204));
        buttonVoltar3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        buttonVoltar3.setForeground(new java.awt.Color(0, 0, 0));
        buttonVoltar3.setText("↩");
        buttonVoltar3.setBorder(null);
        buttonVoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltar3ActionPerformed(evt);
            }
        });

        labelCadastrarFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        labelCadastrarFuncionario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelCadastrarFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        labelCadastrarFuncionario.setText("Cadastrar Funcionário");

        panelCadastrarFuncionario.setBackground(new java.awt.Color(204, 0, 0));
        panelCadastrarFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        labelNomeFuncionario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNomeFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        labelNomeFuncionario.setText("Nome do(a) Funcionário:");

        labelCpfFuncionario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelCpfFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        labelCpfFuncionario.setText("CPF do(a) Funcionário:");

        inputCpfFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        inputCpfFuncionario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputCpfFuncionario.setForeground(new java.awt.Color(51, 51, 51));
        inputCpfFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCpfFuncionarioActionPerformed(evt);
            }
        });

        buttonCadastrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        labelPermissaoFuncionario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelPermissaoFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        labelPermissaoFuncionario.setText("Permissão:");

        comboBoxPermissaoFuncionario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        comboBoxPermissaoFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxPermissaoFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comum", "Especial", "Administrador" }));

        inputNomeFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        inputNomeFuncionario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputNomeFuncionario.setForeground(new java.awt.Color(51, 51, 51));
        inputNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCadastrarFuncionarioLayout = new javax.swing.GroupLayout(panelCadastrarFuncionario);
        panelCadastrarFuncionario.setLayout(panelCadastrarFuncionarioLayout);
        panelCadastrarFuncionarioLayout.setHorizontalGroup(
            panelCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarFuncionarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadastrarFuncionarioLayout.createSequentialGroup()
                        .addComponent(labelPermissaoFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(comboBoxPermissaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadastrarFuncionarioLayout.createSequentialGroup()
                        .addGroup(panelCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNomeFuncionario)
                            .addComponent(labelCpfFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputCpfFuncionario)
                            .addComponent(inputNomeFuncionario))))
                .addContainerGap())
        );
        panelCadastrarFuncionarioLayout.setVerticalGroup(
            panelCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarFuncionarioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpfFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPermissaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPermissaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCadastrarFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCadastrarFuncionario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCadastrarFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCadastrarFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltar3ActionPerformed
        dispose();
    }//GEN-LAST:event_buttonVoltar3ActionPerformed

    private void inputCpfFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCpfFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCpfFuncionarioActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        if (this.getController().validaCampos()) {
            if (this.isUpdate) {
                if (this.getController().alterar()) {
                    JOptionPane.showMessageDialog(rootPane, "Funcionário alterado com sucesso!");
                    this.getTelaPermissoes().getController().atualizarTabela();
                    this.limpaCampos();
                }
            } else {
                if (this.getController().cadastrar()) {
                    JOptionPane.showMessageDialog(rootPane, "Cadastro realizado com sucesso!");
                    this.getTelaPermissoes().getController().atualizarTabela();
                    this.limpaCampos();
                }
            }
        }
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void inputNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonVoltar3;
    private javax.swing.JComboBox<String> comboBoxPermissaoFuncionario;
    private javax.swing.JTextField inputCpfFuncionario;
    private javax.swing.JTextField inputNomeFuncionario;
    private javax.swing.JLabel labelCadastrarFuncionario;
    private javax.swing.JLabel labelCpfFuncionario;
    private javax.swing.JLabel labelNomeFuncionario;
    private javax.swing.JLabel labelPermissaoFuncionario;
    private javax.swing.JPanel panelCadastrarFuncionario;
    // End of variables declaration//GEN-END:variables

    /**
     * Limpas todos os campos da tela
     * @return void
     */
    private void limpaCampos() {
        this.getInputNomeFuncionario().setText("");
        this.getInputCpfFuncionario().setText("");
    }
    
    public TelaPermissoes getTelaPermissoes() {
        return this.telaPermissoes;
    }
    
    public ControllerTelaCadastroFuncionario getController() {
        return controller;
    }

    public JButton getButtonCadastrar() {
        return buttonCadastrar;
    }

    public void setButtonCadastrar(JButton buttonCadastrar) {
        this.buttonCadastrar = buttonCadastrar;
    }

    public JButton getButtonVoltar3() {
        return buttonVoltar3;
    }

    public void setButtonVoltar3(JButton buttonVoltar3) {
        this.buttonVoltar3 = buttonVoltar3;
    }

    public JComboBox<String> getComboBoxPermissaoFuncionario() {
        return comboBoxPermissaoFuncionario;
    }

    public void setComboBoxPermissaoFuncionario(JComboBox<String> comboBoxPermissaoFuncionario) {
        this.comboBoxPermissaoFuncionario = comboBoxPermissaoFuncionario;
    }

    public JTextField getInputCpfFuncionario() {
        return inputCpfFuncionario;
    }

    public void setInputCpfFuncionario(JTextField inputCpfFuncionario) {
        this.inputCpfFuncionario = inputCpfFuncionario;
    }

    public JTextField getInputNomeFuncionario() {
        return inputNomeFuncionario;
    }

    public void setInputNomeFuncionario(JTextField inputNomeFuncionario) {
        this.inputNomeFuncionario = inputNomeFuncionario;
    }

    public JLabel getLabelCadastrarFuncionario() {
        return labelCadastrarFuncionario;
    }

    public void setLabelCadastrarFuncionario(JLabel labelCadastrarFuncionario) {
        this.labelCadastrarFuncionario = labelCadastrarFuncionario;
    }

    public JLabel getLabelCpfFuncionario() {
        return labelCpfFuncionario;
    }

    public void setLabelCpfFuncionario(JLabel labelCpfFuncionario) {
        this.labelCpfFuncionario = labelCpfFuncionario;
    }

    public JLabel getLabelNomeFuncionario() {
        return labelNomeFuncionario;
    }

    public void setLabelNomeFuncionario(JLabel labelNomeFuncionario) {
        this.labelNomeFuncionario = labelNomeFuncionario;
    }

    public JLabel getLabelPermissaoFuncionario() {
        return labelPermissaoFuncionario;
    }

    public void setLabelPermissaoFuncionario(JLabel labelPermissaoFuncionario) {
        this.labelPermissaoFuncionario = labelPermissaoFuncionario;
    }

    public JPanel getPanelCadastrarFuncionario() {
        return panelCadastrarFuncionario;
    }

    public void setPanelCadastrarFuncionario(JPanel panelCadastrarFuncionario) {
        this.panelCadastrarFuncionario = panelCadastrarFuncionario;
    }
    
}
