
package View;

import Controller.ControllerTelaCadastroDoacao;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Tela do sistema para cadastro de novas doações de sangue.
 * 
 * @author - Ruan Pereira
 * @since  - 18/12/2023
 */
public class TelaCadastroDoacao extends javax.swing.JFrame {

    private final ControllerTelaCadastroDoacao controller;
    private final TelaBancoSangue telaBancoSangue;
    
    /**
     * Creates new form TelaCadastroDoacao
     * @param telaBancoSangue
     */
    public TelaCadastroDoacao(TelaBancoSangue telaBancoSangue) {
        initComponents();
        this.controller = new ControllerTelaCadastroDoacao(this);
        this.telaBancoSangue = telaBancoSangue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelInfoDoador = new javax.swing.JPanel();
        checkBoxIsDoador = new javax.swing.JCheckBox();
        labelCpfDoador = new javax.swing.JLabel();
        inputCpfDoador = new javax.swing.JTextField();
        labelNomeDoador = new javax.swing.JLabel();
        inputNomeDoador = new javax.swing.JTextField();
        labelNascimento = new javax.swing.JLabel();
        inputNascimento = new javax.swing.JTextField();
        inputTelefone = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        inputEndereco = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        labelCadastrarDoacao = new javax.swing.JLabel();
        panelInfoSangue = new javax.swing.JPanel();
        labelTipoSangue = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        inputQuantidade = new javax.swing.JTextField();
        buttonCadastrar = new javax.swing.JButton();
        comboBoxTipoSangue = new javax.swing.JComboBox<>();
        buttonVoltar3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelInfoDoador.setBackground(new java.awt.Color(204, 0, 0));
        panelInfoDoador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Doador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        panelInfoDoador.setForeground(new java.awt.Color(51, 51, 51));

        checkBoxIsDoador.setBackground(new java.awt.Color(204, 0, 0));
        checkBoxIsDoador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkBoxIsDoador.setForeground(new java.awt.Color(0, 0, 0));
        checkBoxIsDoador.setText("Já é Doador?");
        checkBoxIsDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxIsDoadorActionPerformed(evt);
            }
        });

        labelCpfDoador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelCpfDoador.setForeground(new java.awt.Color(0, 0, 0));
        labelCpfDoador.setText("CPF do(a) Doador:");

        inputCpfDoador.setBackground(new java.awt.Color(255, 255, 255));
        inputCpfDoador.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputCpfDoador.setForeground(new java.awt.Color(51, 51, 51));
        inputCpfDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCpfDoadorActionPerformed(evt);
            }
        });

        labelNomeDoador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNomeDoador.setForeground(new java.awt.Color(0, 0, 0));
        labelNomeDoador.setText("Nome do(a) Doador:");

        inputNomeDoador.setBackground(new java.awt.Color(255, 255, 255));
        inputNomeDoador.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputNomeDoador.setForeground(new java.awt.Color(51, 51, 51));
        inputNomeDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeDoadorActionPerformed(evt);
            }
        });

        labelNascimento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNascimento.setForeground(new java.awt.Color(0, 0, 0));
        labelNascimento.setText("Data de Nascimento:");

        inputNascimento.setBackground(new java.awt.Color(255, 255, 255));
        inputNascimento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputNascimento.setForeground(new java.awt.Color(51, 51, 51));
        inputNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNascimentoActionPerformed(evt);
            }
        });

        inputTelefone.setBackground(new java.awt.Color(255, 255, 255));
        inputTelefone.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputTelefone.setForeground(new java.awt.Color(51, 51, 51));
        inputTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelefoneActionPerformed(evt);
            }
        });

        labelTelefone.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTelefone.setForeground(new java.awt.Color(0, 0, 0));
        labelTelefone.setText("Telefone:");

        labelEmail.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(0, 0, 0));
        labelEmail.setText("Email:");

        inputEmail.setBackground(new java.awt.Color(255, 255, 255));
        inputEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputEmail.setForeground(new java.awt.Color(51, 51, 51));
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });

        inputEndereco.setBackground(new java.awt.Color(255, 255, 255));
        inputEndereco.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputEndereco.setForeground(new java.awt.Color(51, 51, 51));
        inputEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEnderecoActionPerformed(evt);
            }
        });

        labelEndereco.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelEndereco.setForeground(new java.awt.Color(0, 0, 0));
        labelEndereco.setText("Endereço:");

        javax.swing.GroupLayout panelInfoDoadorLayout = new javax.swing.GroupLayout(panelInfoDoador);
        panelInfoDoador.setLayout(panelInfoDoadorLayout);
        panelInfoDoadorLayout.setHorizontalGroup(
            panelInfoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoDoadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoDoadorLayout.createSequentialGroup()
                        .addGroup(panelInfoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNomeDoador)
                            .addComponent(labelNascimento))
                        .addGap(19, 19, 19)
                        .addGroup(panelInfoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNascimento)
                            .addComponent(inputNomeDoador)))
                    .addGroup(panelInfoDoadorLayout.createSequentialGroup()
                        .addComponent(labelTelefone)
                        .addGap(117, 117, 117)
                        .addComponent(inputTelefone))
                    .addGroup(panelInfoDoadorLayout.createSequentialGroup()
                        .addComponent(labelEmail)
                        .addGap(145, 145, 145)
                        .addComponent(inputEmail))
                    .addGroup(panelInfoDoadorLayout.createSequentialGroup()
                        .addComponent(labelEndereco)
                        .addGap(110, 110, 110)
                        .addComponent(inputEndereco))
                    .addGroup(panelInfoDoadorLayout.createSequentialGroup()
                        .addComponent(checkBoxIsDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelInfoDoadorLayout.createSequentialGroup()
                        .addComponent(labelCpfDoador)
                        .addGap(41, 41, 41)
                        .addComponent(inputCpfDoador)))
                .addContainerGap())
        );
        panelInfoDoadorLayout.setVerticalGroup(
            panelInfoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoDoadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxIsDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelInfoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNomeDoador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputNomeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpfDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCpfDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        labelCadastrarDoacao.setBackground(new java.awt.Color(255, 255, 255));
        labelCadastrarDoacao.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelCadastrarDoacao.setForeground(new java.awt.Color(0, 0, 0));
        labelCadastrarDoacao.setText("Cadastrar Doação");

        panelInfoSangue.setBackground(new java.awt.Color(204, 0, 0));
        panelInfoSangue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Sangue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        labelTipoSangue.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTipoSangue.setForeground(new java.awt.Color(0, 0, 0));
        labelTipoSangue.setText("Tipo Sanguineo:");

        labelQuantidade.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelQuantidade.setForeground(new java.awt.Color(0, 0, 0));
        labelQuantidade.setText("Quantidade:");

        inputQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        inputQuantidade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputQuantidade.setForeground(new java.awt.Color(51, 51, 51));
        inputQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputQuantidadeActionPerformed(evt);
            }
        });

        buttonCadastrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        comboBoxTipoSangue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        comboBoxTipoSangue.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxTipoSangue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O Positivo", "O Negativo", "A Positivo", "A Negativo", "B Positivo", "B negativo", "AB Positivo", "AB Negativo" }));

        javax.swing.GroupLayout panelInfoSangueLayout = new javax.swing.GroupLayout(panelInfoSangue);
        panelInfoSangue.setLayout(panelInfoSangueLayout);
        panelInfoSangueLayout.setHorizontalGroup(
            panelInfoSangueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoSangueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoSangueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoSangueLayout.createSequentialGroup()
                        .addComponent(labelTipoSangue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(comboBoxTipoSangue, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoSangueLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoSangueLayout.createSequentialGroup()
                        .addComponent(labelQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelInfoSangueLayout.setVerticalGroup(
            panelInfoSangueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoSangueLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelInfoSangueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoSangue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTipoSangue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoSangueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonVoltar3.setBackground(new java.awt.Color(204, 204, 204));
        buttonVoltar3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        buttonVoltar3.setForeground(new java.awt.Color(0, 0, 0));
        buttonVoltar3.setText("↩");
        buttonVoltar3.setBorder(null);
        buttonVoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInfoSangue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInfoDoador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCadastrarDoacao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(buttonVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCadastrarDoacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInfoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelInfoSangue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        if (this.getController().validaCampos()) {
            if (this.getController().cadastrar()) {
                JOptionPane.showMessageDialog(null, "Doação realizada com sucesso!");
                this.telaBancoSangue.getController().atualizarTabela();
                this.limpaCampos();
            }
        }
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void inputCpfDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCpfDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCpfDoadorActionPerformed

    private void inputQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputQuantidadeActionPerformed

    private void checkBoxIsDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxIsDoadorActionPerformed
        this.getInputNomeDoador().setVisible(!this.getCheckBoxIsDoador().isSelected());
        this.getInputNascimento().setVisible(!this.getCheckBoxIsDoador().isSelected());
        this.getInputTelefone().setVisible(!this.getCheckBoxIsDoador().isSelected());
        this.getInputEmail().setVisible(!this.getCheckBoxIsDoador().isSelected());
        this.getInputEndereco().setVisible(!this.getCheckBoxIsDoador().isSelected());
        
        this.getLabelNomeDoador().setVisible(!this.getCheckBoxIsDoador().isSelected());
        this.getLabelNascimento().setVisible(!this.getCheckBoxIsDoador().isSelected());
        this.getLabelTelefone().setVisible(!this.getCheckBoxIsDoador().isSelected());
        this.getLabelEmail().setVisible(!this.getCheckBoxIsDoador().isSelected());
        this.getLabelEndereco().setVisible(!this.getCheckBoxIsDoador().isSelected());
    }//GEN-LAST:event_checkBoxIsDoadorActionPerformed

    private void inputNomeDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeDoadorActionPerformed

    private void inputNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNascimentoActionPerformed

    private void inputTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefoneActionPerformed

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void inputEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEnderecoActionPerformed

    private void buttonVoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltar3ActionPerformed
        dispose();
    }//GEN-LAST:event_buttonVoltar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonVoltar3;
    private javax.swing.JCheckBox checkBoxIsDoador;
    private javax.swing.JComboBox<String> comboBoxTipoSangue;
    private javax.swing.JTextField inputCpfDoador;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputEndereco;
    private javax.swing.JTextField inputNascimento;
    private javax.swing.JTextField inputNomeDoador;
    private javax.swing.JTextField inputQuantidade;
    private javax.swing.JTextField inputTelefone;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCadastrarDoacao;
    private javax.swing.JLabel labelCpfDoador;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelNascimento;
    private javax.swing.JLabel labelNomeDoador;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTipoSangue;
    private javax.swing.JPanel panelInfoDoador;
    private javax.swing.JPanel panelInfoSangue;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Limpas todos os campos da tela
     * @return void
     */
    private void limpaCampos() {
        this.getInputNomeDoador().setText("");
        this.getInputCpfDoador().setText("");
        this.getInputNascimento().setText("");
        this.getInputTelefone().setText("");
        this.getInputEmail().setText("");
        this.getInputEndereco().setText("");
        this.getInputQuantidade().setText("");
    }
    
    public ControllerTelaCadastroDoacao getController() {
        return controller;
    }
    
    public JButton getButtonCadastrar() {
        return buttonCadastrar;
    }

    public void setButtonCadastrar(JButton buttonCadastrar) {
        this.buttonCadastrar = buttonCadastrar;
    }

    public JButton getButtonVoltar3() {
        return buttonVoltar3;
    }

    public void setButtonVoltar3(JButton buttonVoltar3) {
        this.buttonVoltar3 = buttonVoltar3;
    }

    public JCheckBox getCheckBoxIsDoador() {
        return checkBoxIsDoador;
    }

    public void setCheckBoxIsDoador(JCheckBox checkBoxIsDoador) {
        this.checkBoxIsDoador = checkBoxIsDoador;
    }

    public JComboBox<String> getComboBoxTipoSangue() {
        return comboBoxTipoSangue;
    }

    public void setComboBoxTipoSangue(JComboBox<String> comboBoxTipoSangue) {
        this.comboBoxTipoSangue = comboBoxTipoSangue;
    }

    public JTextField getInputCpfDoador() {
        return inputCpfDoador;
    }

    public void setInputCpfDoador(JTextField inputCpfDoador) {
        this.inputCpfDoador = inputCpfDoador;
    }

    public JTextField getInputEmail() {
        return inputEmail;
    }

    public void setInputEmail(JTextField inputEmail) {
        this.inputEmail = inputEmail;
    }

    public JTextField getInputEndereco() {
        return inputEndereco;
    }

    public void setInputEndereco(JTextField inputEndereco) {
        this.inputEndereco = inputEndereco;
    }

    public JTextField getInputNascimento() {
        return inputNascimento;
    }

    public void setInputNascimento(JTextField inputNascimento) {
        this.inputNascimento = inputNascimento;
    }

    public JTextField getInputNomeDoador() {
        return inputNomeDoador;
    }

    public void setInputNomeDoador(JTextField inputNomeDoador) {
        this.inputNomeDoador = inputNomeDoador;
    }

    public JTextField getInputQuantidade() {
        return inputQuantidade;
    }

    public void setInputQuantidade(JTextField inputQuantidade) {
        this.inputQuantidade = inputQuantidade;
    }

    public JTextField getInputTelefone() {
        return inputTelefone;
    }

    public void setInputTelefone(JTextField inputTelefone) {
        this.inputTelefone = inputTelefone;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JLabel getLabelCadastrarDoacao() {
        return labelCadastrarDoacao;
    }

    public void setLabelCadastrarDoacao(JLabel labelCadastrarDoacao) {
        this.labelCadastrarDoacao = labelCadastrarDoacao;
    }

    public JLabel getLabelCpfDoador() {
        return labelCpfDoador;
    }

    public void setLabelCpfDoador(JLabel labelCpfDoador) {
        this.labelCpfDoador = labelCpfDoador;
    }

    public JLabel getLabelEmail() {
        return labelEmail;
    }

    public void setLabelEmail(JLabel labelEmail) {
        this.labelEmail = labelEmail;
    }

    public JLabel getLabelEndereco() {
        return labelEndereco;
    }

    public void setLabelEndereco(JLabel labelEndereco) {
        this.labelEndereco = labelEndereco;
    }

    public JLabel getLabelNascimento() {
        return labelNascimento;
    }

    public void setLabelNascimento(JLabel labelNascimento) {
        this.labelNascimento = labelNascimento;
    }

    public JLabel getLabelNomeDoador() {
        return labelNomeDoador;
    }

    public void setLabelNomeDoador(JLabel labelNomeDoador) {
        this.labelNomeDoador = labelNomeDoador;
    }

    public JLabel getLabelQuantidade() {
        return labelQuantidade;
    }

    public void setLabelQuantidade(JLabel labelQuantidade) {
        this.labelQuantidade = labelQuantidade;
    }

    public JLabel getLabelTelefone() {
        return labelTelefone;
    }

    public void setLabelTelefone(JLabel labelTelefone) {
        this.labelTelefone = labelTelefone;
    }

    public JLabel getLabelTipoSangue() {
        return labelTipoSangue;
    }

    public void setLabelTipoSangue(JLabel labelTipoSangue) {
        this.labelTipoSangue = labelTipoSangue;
    }

    public JPanel getPanelInfoDoador() {
        return panelInfoDoador;
    }

    public void setPanelInfoDoador(JPanel panelInfoDoador) {
        this.panelInfoDoador = panelInfoDoador;
    }

    public JPanel getPanelInfoSangue() {
        return panelInfoSangue;
    }

    public void setPanelInfoSangue(JPanel panelInfoSangue) {
        this.panelInfoSangue = panelInfoSangue;
    }

    
}
